### ISSUE TITLE
Header needs to be more organized

### ISSUE THREAD

**Issue by Slothman2b** [Slothman2b/TINFO_230_website#12]
some buttons like the "our team" button aren't that important. we can get rid of buttons to make it cleaner. the mobile site also needs some work. currently, the dark gray buttons are positioned weirdly. maybe a fix is to make the color not gray?

**Comment by Shoyebaktar-shirol** [comment]
@Slothman2b   hello Please assign me this issue i would like to work on that issue.

**Comment by Slothman2b** [comment]
header buttons have been made bigger.

Added underlines for buttons

Changed shape of buttons and drop down menu
